language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
script: "coverage run --source=lxmlwrapper test.py"
after_success:
  coveralls
